name: Build and deploy

on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    name: build java ${{ matrix.java }}
    steps:
      - name: Checkout reposistory
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          server-id: github
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package --no-transfer-progress --file pom.xml

  publish:
    needs: build
    name: Publish ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set POM version from tag
        run: |
          TAG_FULL=${GITHUB_REF#refs/tags/}
          if [[ "$TAG_FULL" == v* ]]; then
            VERSION=${TAG_FULL#v}
            IS_RELEASE=true
          else
            VERSION=$TAG_FULL
            IS_RELEASE=false
          fi
          echo "Tag full: $TAG_FULL, Using version: $VERSION, Is release: $IS_RELEASE"
          sed -i "s|@TAG_VERSION@|${VERSION}|g" pom.xml
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "IS_RELEASE=$IS_RELEASE" >> $GITHUB_ENV

      - name: Set up Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: temurin
          java-version: '17'
          cache: "maven"
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          server-id: central
          server-username: MAVEN_CENTRAL_TOKEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Activate Artifact Signing and Version Suffix
        run: |
          profiles="build-sources-and-javadoc,deploy-to-maven-central"
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            profiles="$profiles,sign-artifacts"
            version_suffix=""
          else
            version_suffix="-SNAPSHOT"
          fi
          echo "MAVEN_PROFILES=$profiles" >> $GITHUB_ENV
          version="${GITHUB_REF_NAME}${version_suffix}"
          echo "VERSION=$version" >> $GITHUB_ENV
      - name: Set Maven version
        run: mvn --batch-mode --no-transfer-progress versions:set -DnewVersion=${VERSION}
      - name: Build and deploy to Maven Central
        run: |
          mvn --batch-mode --no-transfer-progress --activate-profiles ${MAVEN_PROFILES} deploy
        env:
          MAVEN_CENTRAL_TOKEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_CENTRAL_TOKEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
